version: "3"

services:

  goshimmer:
    image: iotaledger/goshimmer
    container_name: iota_goshimmer
    restart: unless-stopped
    volumes:
      - ./mainnetdb:/root/mainnetdb:rw
    ports:
      - "14666:14666/tcp"
      - "14626:14626/udp"
      - "14626:14262/tcp"
    command: "-node-disable-plugins statusscreen"
